"""Add missing menu item fields

Revision ID: 00a7cced88fb
Revises: a0e918c620ac
Create Date: 2026-08-01 22:54:30.615419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a7cced88fb'
down_revision = 'a0e918c620ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_veg', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('portion_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('half_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('full_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('single_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('family_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('jumbo_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_best_seller', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_chef_special', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_chef_special')
        batch_op.drop_column('is_best_seller')
        batch_op.drop_column('jumbo_price')
        batch_op.drop_column('family_price')
        batch_op.drop_column('single_price')
        batch_op.drop_column('full_price')
        batch_op.drop_column('half_price')
        batch_op.drop_column('price')
        batch_op.drop_column('portion_type')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_veg')
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###
