"""Remove unique constraint from email

Revision ID: 310a2c0b2222
Revises: 696d4d748e0d
Create Date: 2026-08-01 18:38:00.236211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310a2c0b2222'
down_revision = '696d4d748e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admins_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('admins_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
