"""add lat lng to orders

Revision ID: 901194df14d6
Revises: 00a7cced88fb
Create Date: 2026-08-02 08:31:14.116483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901194df14d6'
down_revision = '00a7cced88fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
