"""Add customer email OTPs

Revision ID: a2d73817e9b7
Revises: 310a2c0b2222
Create Date: 2026-08-01 19:14:53.290183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d73817e9b7'
down_revision = '310a2c0b2222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_email_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_email_otps_email'), ['email'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('customer_email_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_email_otps_email'))

    op.drop_table('customer_email_otps')
    # ### end Alembic commands ###
