"""empty message

Revision ID: da4233c1650d
Revises: 4bf1ae6f0bb4
Create Date: 2026-08-01 10:44:23.126995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4233c1650d'
down_revision = '4bf1ae6f0bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
